version: "3"
services:
  cgi:
    build: .
    volumes:
      - ./index.html:/var/www/localhost/htdocs/index.html
      - ./hello.py:/var/www/localhost/cgi-bin/hello.py
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf
    ports:
      - "1234:80"
    # I guess we need this for logging...?
    tty: true
