version: "3"
services:
  cgi:
    build: .
    volumes:
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf
      - ./cgi-bin:/var/www/localhost/cgi-bin
    ports:
      - "1234:80"
    # I guess we need this for logging...?
    tty: true
