version: "3"
services:
  cgi:
    build: .
    volumes:
      - ./hello:/var/www/localhost/cgi-bin/hello
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf
    ports:
      - "1234:80"
    # I guess we need this for logging...?
    tty: true
